# Generated by Django 5.0 on 2024-01-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montapp', '0005_facture_utilisateurs_alter_facture_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_depot',
            field=models.DateField(auto_now_add=True, default='2023-01-01'),
            preserve_default=False,
        ),
    ]
